### ISSUE TITLE
how does one go about configuring and using it ?

### ISSUE THREAD

**Issue by priyavadan** [kvaster/iptv-proxy#2]
thanks!

**Comment by kvaster** [comment]
Example (from my config):

iptvproxy.yml

```
host: 127.0.0.1
port: 8089
base_url: https://iptv.mydomain.com
forwarded_pass: mypass
token_salt: mysalt
servers:
- name: ilook
  connections:
  - url: http://xxx/playlist.m3u8
    max_connections: 2
  - url: http://xxx/playlist.m3u8
    max_connections: 2
  - url: http://xxx/playlist.m3u8
    max_connections: 2
  xmltv_url: http://epg.xxx/xmltv.xml.gz
  channel_failed_ms: 1000
allow_anonymous: false
users:
- user1
- user2
```

nginx (used for tls termination):

```
server {
        listen 443 ssl http2;
        server_name iptv.mydomain.com;

        root /var/www/iptv;

        proxy_buffering on;
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k;
        proxy_buffers 2048 16k;

        location / {
                proxy_pass http://127.0.0.1:8089;
                proxy_set_header Forwarded "pass=mypass;baseUrl=https://$host";
        }
}
```

I have three urls from one provider. All urls will give me the same channels, but each url allows only 2 connections same time.

This config will allow me to watch channels on 6 devices same time.

And to launch: `java -Dconfig=config.yml -Dlog.level=debug -jar iptv-proxy-all.jar`
